services:
  app:
    image: diary-front
    build:
      context: ./diary-frontend/
      dockerfile: Dockerfile
    #ports:
    #  - 3000:3000
    #environment:
    #  - REACT_APP_BACKEND_URL=http://localhost:8080/api
    container_name: diary-front
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server
  server:
    image: diary-back
    build:
      context: ./diary-backend
      dockerfile: Dockerfile
    #ports:
    #  - 4000:3000
    #environment:
      #- REDIS_URL=redis://redis:6379
      #- MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
